DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS players;

CREATE TABLE teams (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT NOT NULL 
);

CREATE TABLE players (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    number INT NOT NULL,
    team INT NOT NULL REFERENCES teams(id)
)